### ISSUE TITLE
danieleServadei

### ISSUE THREAD

**Issue by danieleServadei** [soluzionifutura/sf-academy#1]
Track 1, web development

**Comment by vforvalerio87** [comment]
Solo 1?

**Comment by danieleServadei** [comment]
Pensavo di farne uno alla volta nel tempo libero in modo da gestirmi anche con gli impegni scolastici (abbiamo delle veririche a breve), ho chiesto a nico e ha detto che era possibile farlo

**Comment by danieleServadei** [comment]
@vforvalerio87 alla fine faccio tutte e tre le track insieme, ho parlato oggi con bruno :smile:

**Comment by nicofuccella** [comment]
@danieleServadei sei stato invitato come collaboratore della repository contenente il testo della tua prova e la deadline.
