### ISSUE TITLE
Tompa02

### ISSUE THREAD

**Issue by Tompa02** [soluzionifutura/sf-academy#12]
Track 1
Track 2
Track 3

**Comment by nicofuccella** [comment]
@Tompa02 sei stato invitato come collaboratore della repository contenente il testo della tua prova e la deadline. Buona fortuna 👍

**Comment by nicofuccella** [comment]
@Tompa02 a che punto sei? Entro questo mese avevamo in programma di correggere le prove. Nel caso non dovessimo prendere in considerazione la candidatura puoi chiudere la issue
