### ISSUE TITLE
bluborghi

### ISSUE THREAD

**Issue by bluborghi** [soluzionifutura/sf-academy#14]
Track 1,2

**Comment by bluborghi** [comment]
Per caso sono stati disabilitati i labels? Non mi fa mettere l'etichetta della candidatura

**Comment by nicofuccella** [comment]
Ho notato adesso che solo chi ha i permessi di scrittura sulla repository può aggiungere le label.
Ad ogni modo @bluborghi  sei stato invitato come collaboratore della repository contenente il testo della tua prova e la deadline. Buona fortuna 👍
