### ISSUE TITLE
Gulmini

### ISSUE THREAD

**Issue by Gulmini** [soluzionifutura/sf-academy#15]
Track 1, 2

**Comment by nicofuccella** [comment]
@Gulmini sei stato invitato come collaboratore della repository contenente il testo della tua prova e la deadline. Buona fortuna 👍

**Comment by nicofuccella** [comment]
@Gulmini a che punto sei? Entro questo mese avevamo in programma di correggere le prove. Nel caso non dovessimo prendere in considerazione la candidatura puoi chiudere la issue

**Comment by Gulmini** [comment]
Chiudo la issue, non ero sufficientemente pronto

**Comment by nicofuccella** [comment]
Se sei ancora interessato, possiamo valutare di ridurre la complessità della prova. Facci sapere, altrimenti ci sentiamo l'anno prossimo.

**Comment by Gulmini** [comment]
Grazie dell'opportunità ma ho seriamente sottovalutato di tanto il carico e per evitare di lasciare inconclusa di nuovo la prova ci riprovo l'anno prossimo
