### ISSUE TITLE
Frizio03

### ISSUE THREAD

**Issue by Frizio03** [soluzionifutura/sf-academy#17]
Salve, sono Fabrizio Tedeschi e frequento la classe 3F del liceo Spallanzani. Chiedo gentilmente di candidarmi per il percorso/prova di "Web Development".

In attesa di risconto, cordiali saluti,
Fabrizio Tedeschi

**Comment by nicofuccella** [comment]
@Frizio03  sei stato invitato come collaboratore della repository contenente il testo della tua prova e la deadline. Dato il numero di candidature abbiamo ritenuto opportuno aggiungerti anche una componente di infrastruttura. Buona fortuna 👍

**Comment by nicofuccella** [comment]
@Frizio03 a che punto sei. Entro questo mese avevamo in programma di correggere le prove. Nel caso non dovessimo prendere in considerazione la candidatura puoi chiudere la issue

**Comment by Frizio03** [comment]
@nicofuccella grazie, chiudo la issue ma sicuramente invierò un'altra candidatura in un futuro prossimo per ritentare!
