### ISSUE TITLE
AlexFoderaro03

### ISSUE THREAD

**Issue by AlexFoderaro03** [soluzionifutura/sf-academy#20]
Web Development

**Comment by nicofuccella** [comment]
@AlexFoderaro03 sei stato invitato come collaboratore della repository contenente il testo della tua prova e la deadline. Dato il numero di candidature abbiamo ritenuto opportuno aggiungerti anche una componente di infrastruttura. Buona fortuna 👍

**Comment by AlexFoderaro03** [comment]
Ma su EC2 va hostato tutto l'applicativo, che a sua volta utilizza un db su RDS giusto?

**Comment by nicofuccella** [comment]
Si corretto
