### ISSUE TITLE
MatteoBartoli03

### ISSUE THREAD

**Issue by MatteoBartoli03** [soluzionifutura/sf-academy#3]
track 1 web development

**Comment by nicofuccella** [comment]
Sei stato invitato come collaboratore della repository contenente il testo della tua prova e la deadline.

**Comment by MatteoBartoli03** [comment]
Durante il periodo scolastico non sono riuscito a svolgere la prova per vari impegni, mi ero accordato coň Giovanni Bruno per rifarla quest'estate. È possibile?

**Comment by nicofuccella** [comment]
@MatteoBartoli03 sei ancora interessato a portare a termine la prova o posso chiudere la issue?
