### ISSUE TITLE
Candidatura

### ISSUE THREAD

**Issue by boatleel** [soluzionifutura/sf-academy#34]
Mi candido per la prova intern-developer
-Filippo Lelli

**Comment by giowe** [comment]
Ciao @boatleel , procedi pure come da descrizione del readme principale della repo, per qualunque domanda scrivi pure qui

**Comment by boatleel** [comment]
Ciao! Volevo dirvi che questa issue l'ho aperta oggi ma ho iniziato a lavorare alla prova il giorno in cui me l'avete mandata, sono a buon punto direi. Avrei anche una domanda. Quando faccio aggiungere un utente al database, devo considerarla come una specie di registrazione e quindi chiedere sia l username che la password dell'utente che si vuole aggiungere?

**Comment by boatleel** [comment]
Il dubbio alla fine l'ho risolto e ho terminato la prova. Dovrei avere creato la pull request con la soluzione ma non so se ho fatto tutto correttamente perchè non riesco a richiedere la review da nessuno.

**Comment by giowe** [comment]
Tranquillo, pr ricevuta. Ti aggiorniamo a breve. Grazie mille intanto

**Comment by giowe** [comment]
@boatleel da ora in poi continuiamo la conversazione nel thread della pull request
