### ISSUE TITLE
Candidatura

### ISSUE THREAD

**Issue by onemoredavide** [soluzionifutura/sf-academy#36]
Mi candido per la prova [intern-developer](https://github.com/soluzionifutura/sf-academy/blob/master/prove/intern-developer.md)

**Comment by mczanichelli** [comment]
ciao @onemoredavide abbiamo ricevuto la prova, in questi giorni guardiamo tutto e ti facciamo sapere. intanto posso chiederti di inviarmi una copia del tuo curriculum a mariachiara@soluzionifutura.it?

grazie

**Comment by onemoredavide** [comment]
Ok, curriculum inviato.
