### ISSUE TITLE
FrancescoMusi

### ISSUE THREAD

**Issue by FrancescoMusi** [soluzionifutura/sf-academy#4]
candidatura per la 1 track: web development

**Comment by nicofuccella** [comment]
@FrancescoMusi sei stato invitato come collaboratore della repository contenente il testo della tua prova e la deadline.

**Comment by FrancescoMusi** [comment]
non riesco a finire la prova per mancanza di tempo. Scusate e Grazie.

**Comment by nicofuccella** [comment]
@FrancescoMusi sei interessato a riprovare la prova di SF Academy?
