### ISSUE TITLE
Candidatura Filippo Tondelli

### ISSUE THREAD

**Issue by Tond28** [soluzionifutura/sf-academy#45]
Mi candido per la prova Intern-developer

Filippo Tondelli

**Comment by giowe** [comment]
Inizia pure, buon lavoro

**Comment by giowe** [comment]
@Tond28 nello specifico, se e' per la scuola lavoro di questa estate, visto che il tempo e' stretto, sentiamoci gia' per mandare avanti la burocrazia mentre fai la prova.
