### ISSUE TITLE
Ollari Ischimji Dmitri - intern developer

### ISSUE THREAD

**Issue by kanopo** [soluzionifutura/sf-academy#64]

**Comment by giowe** [comment]
Ciao @kanopo , ci sono progressi?

**Comment by kanopo** [comment]
Salve 
Avevo capito male io e aspettavo il "via", ho appena cominciato.
Appena ho fatto le mando tutto.
Chiedo ancora scusa per questo disguido.

Buona giornata 
Ollari Dmitri
