### ISSUE TITLE
Muhamad H. Salman - Exchange microservice

### ISSUE THREAD

**Issue by MHS-20** [soluzionifutura/sf-academy#66]
Candidatura intern con prova exchange-microservice

**Comment by giowe** [comment]
@MHS-20 ciao, ci sono progressi ?

**Comment by MHS-20** [comment]
Si, il codice l'ho finito, sto cercando di fare il container in docker.

**Comment by MHS-20** [comment]
Salve, qualche settimana fa avevo completato anche il container, c'era solo un problema di networking che dovevo risolvere, però in queste settimane sto avendo molti esami ravvicinati e non ho auto tempo di metterci mano. A metà febbraio termina la sessione, dopodiché completerò il progetto se non è troppo tardi. Mi scuso per l'attesa, pensavo di riuscire a completarlo prima dell'inizio degli esami, ma alcuni tool non gli avevo mai usati ed il debugging è sempre  un po' time-consuming. @giowe

**Comment by giowe** [comment]
Certamente! Non preoccuparti per le tempistiche, prenditi il tempo che ti serve
